const ageRoute = require("./ageRoute")
const availabilityRoute = require("./availabilityRoute")
const bookRoute = require("./bookRoute")
const categoryRoute = require("./categoryRoute")
const contactRoute = require("./contactRoute")
const courseRoute = require("./courseRoute")
const examRoute = require("./examRoute")
const faqRoute = require("./faqRoute")
const teamRoute = require("./teamRoute")
const testimonialRoute = require("./testimonialRoute")
const userRoute = require("./userRoute")
const videoRoute = require("./videoRoute")
const webContentRoute = require("./webContentRoute")
const teacherRoute = require("./teacherRoute")


const curriculumRoute = require("./curriculumRoute")
const sectionsRoute = require("./sectionRoute")
const levelsRoute = require("./levelRoute")
const messagesRoute = require("./messageRoute")
const newsletterRoute = require("./newsletterRoute")
const questionRoute = require("./questionRoute")
const orderRoute = require("./orderRoute")
const currencyRoute = require("./currencyRoute")
const solutionRoute = require("./solutionRoute")
const fawaterkRoute = require("./fawaterk")
const dashboardRoute = require("./dashboardRoute")

const meetingsRoute = require("./teamsMeeting")



module.exports = useRoutes = (app) => {
  app.use("/ages", ageRoute)
  app.use("/availabilities", availabilityRoute)
  app.use("/books", bookRoute)
  app.use("/categories", categoryRoute)
  app.use("/contacts", contactRoute)
  app.use("/courses", courseRoute)
  app.use("/exams", examRoute)
  app.use("/faqs", faqRoute)
  app.use("/teams", teamRoute)
  app.use("/testimonials", testimonialRoute)
  app.use("/users", userRoute)
  app.use("/videos", videoRoute)
  app.use("/webcontents", webContentRoute)
  app.use("/teachers", teacherRoute)
  
  app.use("/curriculums", curriculumRoute)
  app.use("/sections", sectionsRoute)
  app.use("/levels" , levelsRoute)
  app.use("/messages" , messagesRoute)
  app.use("/newsletters" , newsletterRoute)
  app.use("/questions" , questionRoute)
  app.use("/orders" , orderRoute)
  app.use("/currencies" , currencyRoute)
  app.use("/solutions" , solutionRoute)
  app.use("/fawaterk" , fawaterkRoute)
  app.use("/dashboard" , dashboardRoute)
  app.use("/CreateMeeting", meetingsRoute)
  console.log("Routes Defined");
};
